name: Release APK

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Sign APK (optional - requires signing key setup)
      run: echo "Skipping APK signing - no signing keys configured"
      # Uncomment and configure if you have signing keys:
      # run: |
      #   echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
      #   ./gradlew assembleRelease \
      #     -Pandroid.injected.signing.store.file=keystore.jks \
      #     -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
      #     -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
      #     -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          Changes in this Release:
          - Auto-generated release from tag ${{ steps.get_version.outputs.VERSION }}
        files: |
          app/build/outputs/apk/release/app-release.apk
        draft: false
        prerelease: false